using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Niantic.Lightship.SharedAR.Colocalization;
using Unity.Netcode;
using TMPro;

[RequireComponent(typeof(SharedSpaceFactory))]
public class ImageTrackingColocalizationManager : MonoBehaviour, IColocalizationRoom
{
    [SerializeField] private Texture2D targetImage;
    [SerializeField] private float tarWidthPhysicalSize;
    [SerializeField] private GameObject connectionUI;
    [SerializeField] private TMP_InputField pinInputField;
    [SerializeField] private TextMeshProUGUI pinText;

    private SharedSpaceFactory sharedSpaceFactory;
    private bool startAsHost;

    private void OnEnable()
    {
        sharedSpaceFactory = GetComponent<SharedSpaceFactory>();
        sharedSpaceFactory.OnSharedSpaceTracking += SharedSpaceStartTracking;
    }
    private void OnDisable()
    {
        sharedSpaceFactory.OnSharedSpaceTracking -= SharedSpaceStartTracking;
    }
    // Start is called before the first frame update
    void Start()
    {
        connectionUI.SetActive(true);
    }

    public void StartNetwokAsHostOrClient(bool isHost) { 
        startAsHost = isHost;
        CreateRoomOptions();
    }
    public void CreateRoomOptions()
    {
        string roomName = pinInputField.text;
        var imageTrackingOptions = ISharedSpaceTrackingOptions.CreateImageTrackingOptions(targetImage, tarWidthPhysicalSize);
        sharedSpaceFactory.CreateRoom(imageTrackingOptions, roomName);
        connectionUI.SetActive(false);
        pinText.gameObject.SetActive(true);
        pinText.text = $"PIN: {roomName}";
        Debug.Log(roomName);
    }

    public void SharedSpaceStartTracking()
    {
        if (startAsHost)
        {
            StartHost();
        }
        else { 
            StartClient();
        }
    }

    public void StartClient()
    {
        NetworkManager.Singleton.StartClient();
    }

    public void StartHost()
    {
        NetworkManager.Singleton.StartHost();
    }

    

}
